name: Test

on:
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/test.yml"
      - "**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, Windows, macOS]
        python_version:
          ["3.13", "3.13t"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: env-marker-example

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "zklaus/packaging"
          ref: "env-marker-free-threading"
          path: packaging

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "zklaus/pip"
          ref: "env-marker-free-threading"
          path: pip

      - uses: actions/setup-python@9e62be81b28222addecf85e47571213eb7680449 # main with free-threading support
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          allow-prereleases: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade ./pip
          python -m pip install ./packaging